// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"` // 旧密码
	NewPassword string `json:"newPassword"` // 新密码（至少8位）
}

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码（明文，传输层加密）
}

type LoginResp struct {
	AccessToken  string   `json:"accessToken"`  // 访问令牌，有效期2小时
	RefreshToken string   `json:"refreshToken"` // 刷新令牌，有效期7天
	ExpiresIn    int64    `json:"expiresIn"`    // 访问令牌剩余秒数
	UserInfo     UserInfo `json:"userInfo"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"` // 刷新令牌
}

type RefreshTokenResp struct {
	AccessToken string `json:"accessToken"` // 新访问令牌
	ExpiresIn   int64  `json:"expiresIn"`   // 新令牌有效期秒数
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}
