// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateDosingEventReq struct {
	TankId    string  `json:"tankId"`          // 槽体ID
	EventTime string  `json:"eventTime"`       // 加药时间（格式：2006-01-02 15:04:05）
	DrugType  string  `json:"drugType"`        // 药品类型：CrO3铬酸酐 H2SO4硫酸 Cr2O3三氧化二铬
	MassGram  float64 `json:"massGram"`        // 加药质量（克）
	Remark    string  `json:"remark,optional"` // 备注
}

type CreateProductionEventReq struct {
	TankId        string  `json:"tankId"`                 // 槽体ID
	StartTime     string  `json:"startTime"`              // 生产开始时间（格式：2006-01-02 15:04:05）
	EndTime       string  `json:"endTime"`                // 生产结束时间
	AmpHour       float64 `json:"ampHour"`                // 实际电量（Ah），优先使用此值
	AreaDm2       float64 `json:"areaDm2,optional"`       // 工件面积（dm²），用于带液量计算
	WorkpieceType string  `json:"workpieceType,optional"` // 工件类型：A平板件 B普通件 C复杂件（影响带液系数选择）
	Remark        string  `json:"remark,optional"`        // 备注
}

type CreateWaterEventReq struct {
	TankId      string  `json:"tankId"`          // 槽体ID
	EventTime   string  `json:"eventTime"`       // 补水时间（格式：2006-01-02 15:04:05）
	VolumeLiter float64 `json:"volumeLiter"`     // 补水量（升）
	Remark      string  `json:"remark,optional"` // 备注
}

type ListDosingEventResp struct {
	Total int64             `json:"total"` // 总数
	List  []DosingEventItem `json:"list"`  // 加药事件列表
}

type ListEventReq struct {
	TankId    string `form:"tankId,optional"`     // 槽体ID过滤
	Page      int    `form:"page,default=1"`      // 页码
	PageSize  int    `form:"pageSize,default=20"` // 每页数量
	StartTime string `form:"startTime,optional"`  // 事件时间范围开始
	EndTime   string `form:"endTime,optional"`    // 事件时间范围结束
}

type ListProductionEventResp struct {
	Total int64                 `json:"total"` // 总数
	List  []ProductionEventItem `json:"list"`  // 生产事件列表
}

type ListWaterEventResp struct {
	Total int64            `json:"total"` // 总数
	List  []WaterEventItem `json:"list"`  // 补水事件列表
}

type TriggerCalcReq struct {
	TankId string `json:"tankId"` // 槽体ID，留空则处理所有槽体
}

type TriggerCalcResp struct {
	ProcessedCount int `json:"processedCount"` // 本次处理的事件数量
}
