// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ExportStateReportReq struct {
	TankId    string `form:"tankId"`             // 槽体ID
	StartTime string `form:"startTime,optional"` // 开始时间
	EndTime   string `form:"endTime,optional"`   // 结束时间
}

type GetStateTrendReq struct {
	TankId    string `form:"tankId"`             // 槽体ID（必填）
	StartTime string `form:"startTime,optional"` // 开始时间（格式：2006-01-02 15:04:05）
	EndTime   string `form:"endTime,optional"`   // 结束时间
	Limit     int    `form:"limit,default=200"`  // 最多返回的数据点数量（默认200）
}

type ModelStateResp struct {
	Id         int64   `json:"id"`         // 状态记录ID
	TankId     string  `json:"tankId"`     // 槽体ID
	CalcTime   string  `json:"calcTime"`   // 计算时刻
	CrO3GPerL  float64 `json:"crO3GPerL"`  // CrO3浓度（g/L）
	Cr3GPerL   float64 `json:"cr3GPerL"`   // Cr3+浓度（g/L）
	TankVolume float64 `json:"tankVolume"` // 槽液体积（升）
	Source     string  `json:"source"`     // 数据来源：init初始化 production生产 dosing加药 water补水 lab化验校正
	Remark     string  `json:"remark"`     // 备注
	CreatedAt  string  `json:"createdAt"`  // 记录创建时间
}

type OverrideStateReq struct {
	TankId    string  `json:"tankId"`            // 槽体ID
	CrO3GPerL float64 `json:"crO3GPerL"`         // 化验CrO3浓度（g/L）
	Cr3GPerL  float64 `json:"cr3GPerL"`          // 化验Cr3+浓度（g/L）
	CalcTime  string  `json:"calcTime,optional"` // 化验时间，为空则使用当前时间
	Remark    string  `json:"remark,optional"`   // 化验备注（如：批次号、化验员）
}

type StateTrendResp struct {
	TankId string           `json:"tankId"` // 槽体ID
	List   []ModelStateResp `json:"list"`   // 状态时间序列
}
