// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserReq struct {
	Username string  `json:"username"`          // 用户名，唯一
	Password string  `json:"password"`          // 初始密码
	Nickname string  `json:"nickname,optional"` // 昵称
	Email    string  `json:"email,optional"`    // 邮箱
	Phone    string  `json:"phone,optional"`    // 手机号
	Status   int     `json:"status"`            // 状态：1启用 0禁用
	Avatar   string  `json:"avatar,optional"`   // 头像URL
	Remark   string  `json:"remark,optional"`
	RoleIds  []int64 `json:"roleIds,optional"` // 角色ID列表
}

type ListUserReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词（用户名/昵称）
	Status   int    `form:"status,optional"`     // 状态过滤：1启用 0禁用
}

type ListUserResp struct {
	Total int64      `json:"total"` // 总数
	List  []UserItem `json:"list"`  // 用户列表
}

type ResetPasswordReq struct {
	Id          int64  `path:"id"`          // 用户ID
	NewPassword string `json:"newPassword"` // 新密码
}

type UpdateUserReq struct {
	Id       int64   `path:"id"`                // 用户ID
	Nickname string  `json:"nickname,optional"` // 昵称
	Email    string  `json:"email,optional"`    // 邮箱
	Phone    string  `json:"phone,optional"`    // 手机号
	Status   int     `json:"status"`            // 状态：1启用 0禁用
	Avatar   string  `json:"avatar,optional"`
	Remark   string  `json:"remark,optional"`  // 头像URL
	RoleIds  []int64 `json:"roleIds,optional"` // 角色ID列表
}

type UserItem struct {
	Id        int64    `json:"id"`       // 用户ID
	Username  string   `json:"username"` // 用户名
	Nickname  string   `json:"nickname"` // 昵称
	Email     string   `json:"email"`    // 邮箱
	Phone     string   `json:"phone"`    // 手机号
	Status    int      `json:"status"`   // 状态
	Avatar    string   `json:"avatar"`
	Remark    string   `json:"remark"`
	Roles     []string `json:"roles"`     // 角色名称列表
	CreatedAt string   `json:"createdAt"` // 创建时间
	UpdatedAt string   `json:"updatedAt"` // 更新时间
}
