// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ListLoginLogReq struct {
	Page      int    `form:"page,default=1"`      // 页码
	PageSize  int    `form:"pageSize,default=20"` // 每页数量
	Username  string `form:"username,optional"`   // 用户名过滤
	Status    int    `form:"status,optional"`     // 状态：1成功 0失败
	StartTime string `form:"startTime,optional"`  // 开始时间（格式：2006-01-02 15:04:05）
	EndTime   string `form:"endTime,optional"`    // 结束时间
}

type ListLoginLogResp struct {
	Total int64          `json:"total"` // 总数
	List  []LoginLogItem `json:"list"`  // 日志列表
}

type ListOperLogReq struct {
	Page      int    `form:"page,default=1"`      // 页码
	PageSize  int    `form:"pageSize,default=20"` // 每页数量
	OperName  string `form:"operName,optional"`   // 操作人
	OperType  string `form:"operType,optional"`   // 操作类型
	Status    int    `form:"status,optional"`     // 状态：1成功 0失败
	StartTime string `form:"startTime,optional"`  // 开始时间
	EndTime   string `form:"endTime,optional"`    // 结束时间
}

type ListOperLogResp struct {
	Total int64         `json:"total"` // 总数
	List  []OperLogItem `json:"list"`  // 日志列表
}
