// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateMenuReq struct {
	ParentId  int64  `json:"parentId,optional"`  // 父菜单ID，顶级为0
	MenuName  string `json:"menuName"`           // 菜单名称
	MenuType  int64  `json:"menuType"`           // 菜单类型：1目录 2菜单 3按钮
	Path      string `json:"path,optional"`      // 路由路径（菜单/目录必填）
	Component string `json:"component,optional"` // 组件路径（菜单必填）
	Icon      string `json:"icon,optional"`      // 图标名称
	Sort      int    `json:"sort,optional"`      // 排序序号，越小越靠前
	Perms     string `json:"perms,optional"`     // 权限标识（如：system:user:list）
	Status    int    `json:"status"`             // 状态：1显示 0隐藏
	Remark    string `json:"remark,optional"`
}

type MenuTreeResp struct {
	List []MenuItem `json:"list"` // 菜单树形列表
}

type UpdateMenuReq struct {
	Id        int64   `path:"id"`                 // 菜单ID
	ParentId  *int64  `json:"parentId,optional"`  // 父菜单ID，顶级为0
	MenuName  *string `json:"menuName,optional"`  // 菜单名称
	MenuType  *int    `json:"menuType,optional"`  // 菜单类型
	Path      *string `json:"path,optional"`      // 路由路径
	Component *string `json:"component,optional"` // 组件路径
	Icon      *string `json:"icon,optional"`      // 图标
	Sort      *int    `json:"sort,optional"`      // 排序
	Perms     *string `json:"perms,optional"`     // 权限标识
	Status    *int    `json:"status,optional"`    // 菜单可用性
	Visible   *int    `json:"visible,optional"`   // 可见性
	Remark    *string `json:"remark,optional"`
}
