// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateRoleReq struct {
	RoleName string  `json:"roleName"`         // 角色名称
	RoleCode string  `json:"roleCode"`         // 角色编码，唯一（如：admin, operator）
	Remark   string  `json:"remark,optional"`  // 备注
	MenuIds  []int64 `json:"menuIds,optional"` // 关联菜单ID列表
	ApiIds   []int64 `json:"apiIds,optional"`  // 关联接口ID列表
}

type ListRoleReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词
}

type ListRoleResp struct {
	Total int64      `json:"total"` // 总数
	List  []RoleItem `json:"list"`  // 角色列表
}

type RoleItem struct {
	Id        int64  `json:"id"`        // 角色ID
	RoleName  string `json:"roleName"`  // 角色名称
	RoleCode  string `json:"roleCode"`  // 角色编码
	Remark    string `json:"remark"`    // 备注
	CreatedAt string `json:"createdAt"` // 创建时间
}

type UpdateRoleReq struct {
	Id       int64   `path:"id"`               // 角色ID
	RoleName string  `json:"roleName"`         // 角色名称
	Remark   string  `json:"remark,optional"`  // 备注
	MenuIds  []int64 `json:"menuIds,optional"` // 关联菜单ID列表
	ApiIds   []int64 `json:"apiIds,optional"`  // 关联接口ID列表
}
