// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FileInfoResp struct {
	FileId   int64  `json:"fileId"`   // 文件ID
	FileName string `json:"fileName"` // 原始文件名
	FileURL  string `json:"fileUrl"`  // 文件访问URL
	FileSize int64  `json:"fileSize"` // 文件大小（字节）
	MimeType string `json:"mimeType"` // MIME类型
}

type ListFileReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 文件名关键词
}

type ListFileResp struct {
	Total int64          `json:"total"` // 总数
	List  []FileInfoResp `json:"list"`  // 文件列表
}
