// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateDictDataReq struct {
	DictTypeId int    `json:"dictTypeId" validate:"required"` // 字典类型ID
	DictLabel  string `json:"dictLabel" validate:"required"`  // 字典标签（显示文本）
	DictValue  string `json:"dictValue" validate:"required"`  // 字典值（实际存储值）
	Sort       int    `json:"sort,optional"`                  // 排序序号
	Remark     string `json:"remark,optional"`                // 备注
	Status     int    `json:"status"`                         // 状态：1启用 0禁用
}

type CreateDictTypeReq struct {
	DictName string `json:"dictName" validate:"required"` // 字典名称
	DictCode string `json:"dictCode"`                     // 字典类型（唯一编码，如：sys_user_status）
	Remark   string `json:"remark,optional"`              // 备注
	Status   int    `json:"status"`                       // 状态：1启用 0禁用
}

type ListDictDataResp struct {
	Total int64          `json:"total"` // 总数
	List  []DictDataItem `json:"list"`  // 字典数据列表
}

type ListDictTypeReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词
}

type ListDictTypeResp struct {
	Total int            `json:"total"` // 总数
	List  []DictTypeItem `json:"list"`  // 字典类型列表
}

type UpdateDictDataReq struct {
	Id         int     `path:"id" validate:"required"`         // 字典数据ID
	DictTypeId int     `json:"dictTypeId" validate:"required"` // 字典类型ID
	DictLabel  string  `json:"dictLabel" validate:"required"`  // 字典标签
	DictValue  string  `json:"dictValue" validate:"required"`  // 字典值
	Sort       *int    `json:"sort,optional"`                  // 排序
	Remark     *string `json:"remark,optional"`                // 备注
	Status     *int    `json:"status"`                         // 状态
}

type UpdateDictTypeReq struct {
	Id       int     `path:"id" validate:"required"` // 字典类型ID
	DictName *string `json:"dictName,optional"`      // 字典名称
	DictCode *string `json:"dictCode,optional" `     // 字典类型（唯一编码，如：sys_user_status）
	Remark   *string `json:"remark,optional"`        // 备注
	Status   *int    `json:"status,optional"`        // 状态
}
