// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateApiReq struct {
	ApiName string `json:"apiName"`         // 接口名称
	ApiPath string `json:"apiPath"`         // 接口路径（如：/api/system/user/:id）
	Method  string `json:"method"`          // HTTP方法：GET POST PUT DELETE
	Group   string `json:"group"`           // 接口分组（如：system, plating）
	Remark  string `json:"remark,optional"` // 备注
}

type ListApiReq struct {
	Page     int    `form:"page,default=1"`      // 页码
	PageSize int    `form:"pageSize,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`    // 关键词（接口名/路径）
	Group    string `form:"group,optional"`      // 分组过滤
}

type ListApiResp struct {
	Total int64     `json:"total"` // 总数
	List  []ApiItem `json:"list"`  // 接口列表
}

type UpdateApiReq struct {
	Id      int64  `path:"id"`              // 接口ID
	ApiName string `json:"apiName"`         // 接口名称
	Group   string `json:"group"`           // 接口分组
	Remark  string `json:"remark,optional"` // 备注
}
