// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiItem struct {
	Id        int64  `json:"id"`        // 接口ID
	ApiName   string `json:"apiName"`   // 接口名称
	ApiPath   string `json:"apiPath"`   // 接口路径
	Method    string `json:"method"`    // HTTP方法
	Group     string `json:"group"`     // 接口分组
	Remark    string `json:"remark"`    // 备注
	CreatedAt string `json:"createdAt"` // 创建时间
}

type DictDataItem struct {
	Id        int64  `json:"id"`        // 字典数据ID
	DictType  string `json:"dictType"`  // 所属字典类型
	DictLabel string `json:"dictLabel"` // 字典标签
	DictValue string `json:"dictValue"` // 字典值
	Sort      int    `json:"sort"`      // 排序
	Remark    string `json:"remark"`    // 备注
	Status    int    `json:"status"`    // 状态
}

type DictTypeItem struct {
	Id        int64  `json:"id"`        // 字典类型ID
	DictName  string `json:"dictName"`  // 字典名称
	DictType  string `json:"dictType"`  // 字典类型编码
	Remark    string `json:"remark"`    // 备注
	Status    int    `json:"status"`    // 状态
	CreatedAt string `json:"createdAt"` // 创建时间
}

type DosingEventItem struct {
	Id          int64   `json:"id"`          // 事件ID
	TankId      string  `json:"tankId"`      // 槽体ID
	EventTime   string  `json:"eventTime"`   // 加药时间
	DrugType    string  `json:"drugType"`    // 药品类型
	MassGram    float64 `json:"massGram"`    // 加药质量（克）
	IsProcessed int     `json:"isProcessed"` // 是否已处理
	Remark      string  `json:"remark"`      // 备注
	CreatedAt   string  `json:"createdAt"`   // 创建时间
}

type GetLatestStateReq struct {
	TankId string `path:"tankId"` // 槽体ID
}

type LoginLogItem struct {
	Id        int64  `json:"id"`        // 日志ID
	Username  string `json:"username"`  // 用户名
	Ip        string `json:"ip"`        // 登录IP
	UserAgent string `json:"userAgent"` // 浏览器信息
	Status    int    `json:"status"`    // 登录状态：1成功 0失败
	Msg       string `json:"msg"`       // 提示消息
	LoginTime string `json:"loginTime"` // 登录时间
}

type MenuItem struct {
	Id        int64      `json:"id"`                // 菜单ID
	ParentId  int64      `json:"parentId"`          // 父菜单ID
	MenuName  string     `json:"menuName"`          // 菜单名称
	MenuType  int64      `json:"menuType"`          // 菜单类型
	Path      string     `json:"path"`              // 路由路径
	Component string     `json:"component"`         // 组件路径
	Icon      string     `json:"icon"`              // 图标
	Sort      int64      `json:"sort"`              // 排序
	Perms     string     `json:"perms"`             // 权限标识
	Status    int        `json:"status"`            // 状态
	Children  []MenuItem `json:"children,optional"` // 子菜单列表
}

type OperLogItem struct {
	Id         int64  `json:"id"`         // 日志ID
	OperName   string `json:"operName"`   // 操作人名称
	OperType   string `json:"operType"`   // 操作类型（create/update/delete/query）
	Module     string `json:"module"`     // 操作模块
	Method     string `json:"method"`     // HTTP方法
	ReqUrl     string `json:"reqUrl"`     // 请求URL
	ReqParam   string `json:"reqParam"`   // 请求参数
	RespResult string `json:"respResult"` // 响应结果
	Status     int    `json:"status"`     // 状态：1成功 0失败
	Ip         string `json:"ip"`         // 操作IP
	OperTime   string `json:"operTime"`   // 操作时间
	Duration   int64  `json:"duration"`   // 耗时（毫秒）
}

type ProductionEventItem struct {
	Id            int64   `json:"id"`            // 事件ID
	TankId        string  `json:"tankId"`        // 槽体ID
	StartTime     string  `json:"startTime"`     // 生产开始时间
	EndTime       string  `json:"endTime"`       // 生产结束时间
	AmpHour       float64 `json:"ampHour"`       // 电量（Ah）
	AreaDm2       float64 `json:"areaDm2"`       // 工件面积（dm²）
	WorkpieceType string  `json:"workpieceType"` // 工件类型
	IsProcessed   int     `json:"isProcessed"`   // 是否已被模型处理：1已处理 0待处理
	Remark        string  `json:"remark"`        // 备注
	CreatedAt     string  `json:"createdAt"`     // 记录创建时间
}

type UserInfo struct {
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
	Nickname string     `json:"nickname"`
	Email    string     `json:"email"`
	Phone    string     `json:"phone"`
	Avatar   string     `json:"avatar,optional"`
	Roles    []string   `json:"roles"`
	Menus    []MenuItem `json:"menus"`
}

type UserInfoReq struct {
}

type WaterEventItem struct {
	Id          int64   `json:"id"`          // 事件ID
	TankId      string  `json:"tankId"`      // 槽体ID
	EventTime   string  `json:"eventTime"`   // 补水时间
	VolumeLiter float64 `json:"volumeLiter"` // 补水量（升）
	IsProcessed int     `json:"isProcessed"` // 是否已处理
	Remark      string  `json:"remark"`      // 备注
	CreatedAt   string  `json:"createdAt"`   // 创建时间
}
