// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiItem struct {
	Id        int64  `json:"id"`        // 接口ID
	ApiName   string `json:"apiName"`   // 接口名称
	ApiPath   string `json:"apiPath"`   // 接口路径
	Method    string `json:"method"`    // HTTP方法
	Group     string `json:"group"`     // 接口分组
	Remark    string `json:"remark"`    // 备注
	CreatedAt string `json:"createdAt"` // 创建时间
}

type ApiOption struct {
	Id      int64  `json:"id"`      // 接口ID
	ApiName string `json:"apiName"` // 接口名称
	ApiPath string `json:"apiPath"` // 接口路径,如：/api/system/user
	Remark  string `json:"remark"`  // 角色编码
}

type DictDataItem struct {
	Id        int64  `json:"id"`        // 字典数据ID
	DictType  string `json:"dictType"`  // 所属字典类型
	DictLabel string `json:"dictLabel"` // 字典标签
	DictValue string `json:"dictValue"` // 字典值
	Sort      int    `json:"sort"`      // 排序
	Remark    string `json:"remark"`    // 备注
	Status    int    `json:"status"`    // 状态
}

type DictTypeItem struct {
	Id        int64  `json:"id"`        // 字典类型ID
	DictName  string `json:"dictName"`  // 字典名称
	DictType  string `json:"dictType"`  // 字典类型编码
	Remark    string `json:"remark"`    // 备注
	Status    int    `json:"status"`    // 状态
	CreatedAt string `json:"createdAt"` // 创建时间
}

type LoginLogItem struct {
	Id        int64  `json:"id"`        // 日志ID
	Username  string `json:"username"`  // 用户名
	Ip        string `json:"ip"`        // 登录IP
	UserAgent string `json:"userAgent"` // 浏览器信息
	Status    int    `json:"status"`    // 登录状态：1成功 0失败
	Msg       string `json:"msg"`       // 提示消息
	LoginTime string `json:"loginTime"` // 登录时间
}

type MenuItem struct {
	Id        int64      `json:"id"`                // 菜单ID
	ParentId  int64      `json:"parentId"`          // 父菜单ID
	MenuName  string     `json:"menuName"`          // 菜单名称
	MenuType  int64      `json:"menuType"`          // 菜单类型
	Path      string     `json:"path"`              // 路由路径
	Component string     `json:"component"`         // 组件路径
	Icon      string     `json:"icon"`              // 图标
	Sort      int64      `json:"sort"`              // 排序
	Perms     string     `json:"perms"`             // 权限标识
	Status    int        `json:"status"`            // 状态
	Children  []MenuItem `json:"children,optional"` // 子菜单列表
}

type OperLogItem struct {
	Id         int64  `json:"id"`         // 日志ID
	OperName   string `json:"operName"`   // 操作人名称
	OperType   string `json:"operType"`   // 操作类型（create/update/delete/query）
	Module     string `json:"module"`     // 操作模块
	Method     string `json:"method"`     // HTTP方法
	ReqUrl     string `json:"reqUrl"`     // 请求URL
	ReqParam   string `json:"reqParam"`   // 请求参数
	RespResult string `json:"respResult"` // 响应结果
	Status     int    `json:"status"`     // 状态：1成功 0失败
	Ip         string `json:"ip"`         // 操作IP
	OperTime   string `json:"operTime"`   // 操作时间
	Duration   int64  `json:"duration"`   // 耗时（毫秒）
}

type RoleOption struct {
	Id       int64  `json:"id"`       // 角色ID
	RoleName string `json:"roleName"` // 角色名称
	RoleCode string `json:"roleCode"` // 角色编码
}

type UserInfo struct {
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
	Nickname string     `json:"nickname"`
	Email    string     `json:"email"`
	Phone    string     `json:"phone"`
	Avatar   string     `json:"avatar,optional"`
	Roles    []string   `json:"roles"`
	Menus    []MenuItem `json:"menus"`
}

type UserInfoReq struct {
}
