// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package plate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	plateTankConfigFieldNames          = builder.RawFieldNames(&PlateTankConfig{})
	plateTankConfigRows                = strings.Join(plateTankConfigFieldNames, ",")
	plateTankConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(plateTankConfigFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	plateTankConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(plateTankConfigFieldNames, "`tank_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingPlateTankConfigTankIdPrefix = "cache:plating:plateTankConfig:tankId:"
)

type (
	plateTankConfigModel interface {
		Insert(ctx context.Context, data *PlateTankConfig) (sql.Result, error)
		FindOne(ctx context.Context, tankId string) (*PlateTankConfig, error)
		Update(ctx context.Context, data *PlateTankConfig) error
		Delete(ctx context.Context, tankId string) error
	}

	defaultPlateTankConfigModel struct {
		sqlc.CachedConn
		table string
	}

	PlateTankConfig struct {
		TankId       string       `db:"tank_id"`         // 槽体ID（主键，如：TANK-001）
		TankName     string       `db:"tank_name"`       // 槽体名称
		VolumeLiters float64      `db:"volume_liters"`   // 槽体容积（升）
		DensityGPerL float64      `db:"density_g_per_l"` // 镀液密度（g/L）
		DCro3GPerAh  float64      `db:"d_cro3_g_per_ah"` // CrO3消耗系数（g/Ah），法拉第系数
		DCr3GPerAh   float64      `db:"d_cr3_g_per_ah"`  // Cr3+生成系数（g/Ah）
		CarryoverA   float64      `db:"carryover_a"`     // 带出系数A（随工件面积）
		CarryoverB   float64      `db:"carryover_b"`     // 带出系数B（随工件数量）
		CarryoverC   float64      `db:"carryover_c"`     // 带出系数C（固定带出）
		IsActive     int64        `db:"is_active"`       // 是否激活：1=激活，0=停用
		Remark       string       `db:"remark"`          // 备注
		CreatedAt    time.Time    `db:"created_at"`      // 创建时间
		UpdatedAt    time.Time    `db:"updated_at"`      // 更新时间
		DeletedAt    sql.NullTime `db:"deleted_at"`      // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newPlateTankConfigModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlateTankConfigModel {
	return &defaultPlateTankConfigModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`plate_tank_config`",
	}
}

func (m *defaultPlateTankConfigModel) Delete(ctx context.Context, tankId string) error {
	platingPlateTankConfigTankIdKey := fmt.Sprintf("%s%v", cachePlatingPlateTankConfigTankIdPrefix, tankId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `tank_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, tankId)
	}, platingPlateTankConfigTankIdKey)
	return err
}

func (m *defaultPlateTankConfigModel) FindOne(ctx context.Context, tankId string) (*PlateTankConfig, error) {
	platingPlateTankConfigTankIdKey := fmt.Sprintf("%s%v", cachePlatingPlateTankConfigTankIdPrefix, tankId)
	var resp PlateTankConfig
	err := m.QueryRowCtx(ctx, &resp, platingPlateTankConfigTankIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `tank_id` = ? limit 1", plateTankConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tankId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlateTankConfigModel) Insert(ctx context.Context, data *PlateTankConfig) (sql.Result, error) {
	platingPlateTankConfigTankIdKey := fmt.Sprintf("%s%v", cachePlatingPlateTankConfigTankIdPrefix, data.TankId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, plateTankConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TankId, data.TankName, data.VolumeLiters, data.DensityGPerL, data.DCro3GPerAh, data.DCr3GPerAh, data.CarryoverA, data.CarryoverB, data.CarryoverC, data.IsActive, data.Remark, data.DeletedAt)
	}, platingPlateTankConfigTankIdKey)
	return ret, err
}

func (m *defaultPlateTankConfigModel) Update(ctx context.Context, data *PlateTankConfig) error {
	platingPlateTankConfigTankIdKey := fmt.Sprintf("%s%v", cachePlatingPlateTankConfigTankIdPrefix, data.TankId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `tank_id` = ?", m.table, plateTankConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TankName, data.VolumeLiters, data.DensityGPerL, data.DCro3GPerAh, data.DCr3GPerAh, data.CarryoverA, data.CarryoverB, data.CarryoverC, data.IsActive, data.Remark, data.DeletedAt, data.TankId)
	}, platingPlateTankConfigTankIdKey)
	return err
}

func (m *defaultPlateTankConfigModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingPlateTankConfigTankIdPrefix, primary)
}

func (m *defaultPlateTankConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `tank_id` = ? limit 1", plateTankConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlateTankConfigModel) tableName() string {
	return m.table
}
