// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package plate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	plateDosingEventsFieldNames          = builder.RawFieldNames(&PlateDosingEvents{})
	plateDosingEventsRows                = strings.Join(plateDosingEventsFieldNames, ",")
	plateDosingEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(plateDosingEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	plateDosingEventsRowsWithPlaceHolder = strings.Join(stringx.Remove(plateDosingEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingPlateDosingEventsIdPrefix = "cache:plating:plateDosingEvents:id:"
)

type (
	plateDosingEventsModel interface {
		Insert(ctx context.Context, data *PlateDosingEvents) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PlateDosingEvents, error)
		Update(ctx context.Context, data *PlateDosingEvents) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPlateDosingEventsModel struct {
		sqlc.CachedConn
		table string
	}

	PlateDosingEvents struct {
		Id          int64        `db:"id"`           // 事件ID
		TankId      string       `db:"tank_id"`      // 关联槽体ID
		EventTime   time.Time    `db:"event_time"`   // 加药时间
		Chemical    string       `db:"chemical"`     // 化学品名称，如：CrO3、H2SO4
		AmountGrams float64      `db:"amount_grams"` // 加入量（克）
		Processed   int64        `db:"processed"`    // 是否已被模型处理：1=已处理，0=未处理
		Remark      string       `db:"remark"`       // 备注
		CreatedAt   time.Time    `db:"created_at"`   // 创建时间
		DeletedAt   sql.NullTime `db:"deleted_at"`   // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newPlateDosingEventsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlateDosingEventsModel {
	return &defaultPlateDosingEventsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`plate_dosing_events`",
	}
}

func (m *defaultPlateDosingEventsModel) Delete(ctx context.Context, id int64) error {
	platingPlateDosingEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateDosingEventsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingPlateDosingEventsIdKey)
	return err
}

func (m *defaultPlateDosingEventsModel) FindOne(ctx context.Context, id int64) (*PlateDosingEvents, error) {
	platingPlateDosingEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateDosingEventsIdPrefix, id)
	var resp PlateDosingEvents
	err := m.QueryRowCtx(ctx, &resp, platingPlateDosingEventsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateDosingEventsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlateDosingEventsModel) Insert(ctx context.Context, data *PlateDosingEvents) (sql.Result, error) {
	platingPlateDosingEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateDosingEventsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, plateDosingEventsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TankId, data.EventTime, data.Chemical, data.AmountGrams, data.Processed, data.Remark, data.DeletedAt)
	}, platingPlateDosingEventsIdKey)
	return ret, err
}

func (m *defaultPlateDosingEventsModel) Update(ctx context.Context, data *PlateDosingEvents) error {
	platingPlateDosingEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateDosingEventsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, plateDosingEventsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TankId, data.EventTime, data.Chemical, data.AmountGrams, data.Processed, data.Remark, data.DeletedAt, data.Id)
	}, platingPlateDosingEventsIdKey)
	return err
}

func (m *defaultPlateDosingEventsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingPlateDosingEventsIdPrefix, primary)
}

func (m *defaultPlateDosingEventsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateDosingEventsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlateDosingEventsModel) tableName() string {
	return m.table
}
