// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package plate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	plateWaterEventsFieldNames          = builder.RawFieldNames(&PlateWaterEvents{})
	plateWaterEventsRows                = strings.Join(plateWaterEventsFieldNames, ",")
	plateWaterEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(plateWaterEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	plateWaterEventsRowsWithPlaceHolder = strings.Join(stringx.Remove(plateWaterEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingPlateWaterEventsIdPrefix = "cache:plating:plateWaterEvents:id:"
)

type (
	plateWaterEventsModel interface {
		Insert(ctx context.Context, data *PlateWaterEvents) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PlateWaterEvents, error)
		Update(ctx context.Context, data *PlateWaterEvents) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPlateWaterEventsModel struct {
		sqlc.CachedConn
		table string
	}

	PlateWaterEvents struct {
		Id          int64        `db:"id"`           // 事件ID
		TankId      string       `db:"tank_id"`      // 关联槽体ID
		EventTime   time.Time    `db:"event_time"`   // 补水时间
		WaterLiters float64      `db:"water_liters"` // 补水量（升）
		Processed   int64        `db:"processed"`    // 是否已被模型处理：1=已处理，0=未处理
		Remark      string       `db:"remark"`       // 备注
		CreatedAt   time.Time    `db:"created_at"`   // 创建时间
		DeletedAt   sql.NullTime `db:"deleted_at"`   // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newPlateWaterEventsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlateWaterEventsModel {
	return &defaultPlateWaterEventsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`plate_water_events`",
	}
}

func (m *defaultPlateWaterEventsModel) Delete(ctx context.Context, id int64) error {
	platingPlateWaterEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateWaterEventsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingPlateWaterEventsIdKey)
	return err
}

func (m *defaultPlateWaterEventsModel) FindOne(ctx context.Context, id int64) (*PlateWaterEvents, error) {
	platingPlateWaterEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateWaterEventsIdPrefix, id)
	var resp PlateWaterEvents
	err := m.QueryRowCtx(ctx, &resp, platingPlateWaterEventsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateWaterEventsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlateWaterEventsModel) Insert(ctx context.Context, data *PlateWaterEvents) (sql.Result, error) {
	platingPlateWaterEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateWaterEventsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, plateWaterEventsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TankId, data.EventTime, data.WaterLiters, data.Processed, data.Remark, data.DeletedAt)
	}, platingPlateWaterEventsIdKey)
	return ret, err
}

func (m *defaultPlateWaterEventsModel) Update(ctx context.Context, data *PlateWaterEvents) error {
	platingPlateWaterEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateWaterEventsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, plateWaterEventsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TankId, data.EventTime, data.WaterLiters, data.Processed, data.Remark, data.DeletedAt, data.Id)
	}, platingPlateWaterEventsIdKey)
	return err
}

func (m *defaultPlateWaterEventsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingPlateWaterEventsIdPrefix, primary)
}

func (m *defaultPlateWaterEventsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateWaterEventsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlateWaterEventsModel) tableName() string {
	return m.table
}
