// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package plate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	plateProductionEventsFieldNames          = builder.RawFieldNames(&PlateProductionEvents{})
	plateProductionEventsRows                = strings.Join(plateProductionEventsFieldNames, ",")
	plateProductionEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(plateProductionEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	plateProductionEventsRowsWithPlaceHolder = strings.Join(stringx.Remove(plateProductionEventsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingPlateProductionEventsIdPrefix = "cache:plating:plateProductionEvents:id:"
)

type (
	plateProductionEventsModel interface {
		Insert(ctx context.Context, data *PlateProductionEvents) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PlateProductionEvents, error)
		Update(ctx context.Context, data *PlateProductionEvents) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPlateProductionEventsModel struct {
		sqlc.CachedConn
		table string
	}

	PlateProductionEvents struct {
		Id             int64        `db:"id"`               // 事件ID
		TankId         string       `db:"tank_id"`          // 关联槽体ID
		EventTime      time.Time    `db:"event_time"`       // 事件发生时间
		BatchStartTime time.Time    `db:"batch_start_time"` // 批次开始时间
		PartCount      int64        `db:"part_count"`       // 本批次工件数量（件）
		PartAreaDm2    float64      `db:"part_area_dm2"`    // 工件总面积（dm2）
		CarryoverType  string       `db:"carryover_type"`   // 带出类型：A/B/C（对应carryover_a/b/c）
		AhThisBatch    float64      `db:"ah_this_batch"`    // 本批次实际Ah数（安培时）
		AhCalculated   float64      `db:"ah_calculated"`    // 模型计算使用的Ah（可能来自TDEngine或手工录入）
		Processed      int64        `db:"processed"`        // 是否已被模型计算处理：1=已处理，0=未处理
		Remark         string       `db:"remark"`           // 备注
		CreatedAt      time.Time    `db:"created_at"`       // 创建时间
		DeletedAt      sql.NullTime `db:"deleted_at"`       // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newPlateProductionEventsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlateProductionEventsModel {
	return &defaultPlateProductionEventsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`plate_production_events`",
	}
}

func (m *defaultPlateProductionEventsModel) Delete(ctx context.Context, id int64) error {
	platingPlateProductionEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateProductionEventsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingPlateProductionEventsIdKey)
	return err
}

func (m *defaultPlateProductionEventsModel) FindOne(ctx context.Context, id int64) (*PlateProductionEvents, error) {
	platingPlateProductionEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateProductionEventsIdPrefix, id)
	var resp PlateProductionEvents
	err := m.QueryRowCtx(ctx, &resp, platingPlateProductionEventsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateProductionEventsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlateProductionEventsModel) Insert(ctx context.Context, data *PlateProductionEvents) (sql.Result, error) {
	platingPlateProductionEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateProductionEventsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, plateProductionEventsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TankId, data.EventTime, data.BatchStartTime, data.PartCount, data.PartAreaDm2, data.CarryoverType, data.AhThisBatch, data.AhCalculated, data.Processed, data.Remark, data.DeletedAt)
	}, platingPlateProductionEventsIdKey)
	return ret, err
}

func (m *defaultPlateProductionEventsModel) Update(ctx context.Context, data *PlateProductionEvents) error {
	platingPlateProductionEventsIdKey := fmt.Sprintf("%s%v", cachePlatingPlateProductionEventsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, plateProductionEventsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TankId, data.EventTime, data.BatchStartTime, data.PartCount, data.PartAreaDm2, data.CarryoverType, data.AhThisBatch, data.AhCalculated, data.Processed, data.Remark, data.DeletedAt, data.Id)
	}, platingPlateProductionEventsIdKey)
	return err
}

func (m *defaultPlateProductionEventsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingPlateProductionEventsIdPrefix, primary)
}

func (m *defaultPlateProductionEventsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateProductionEventsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlateProductionEventsModel) tableName() string {
	return m.table
}
