// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package plate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	plateModelStateFieldNames          = builder.RawFieldNames(&PlateModelState{})
	plateModelStateRows                = strings.Join(plateModelStateFieldNames, ",")
	plateModelStateRowsExpectAutoSet   = strings.Join(stringx.Remove(plateModelStateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	plateModelStateRowsWithPlaceHolder = strings.Join(stringx.Remove(plateModelStateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingPlateModelStateIdPrefix = "cache:plating:plateModelState:id:"
)

type (
	plateModelStateModel interface {
		Insert(ctx context.Context, data *PlateModelState) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PlateModelState, error)
		Update(ctx context.Context, data *PlateModelState) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPlateModelStateModel struct {
		sqlc.CachedConn
		table string
	}

	PlateModelState struct {
		Id         int64        `db:"id"`           // 主键ID
		TankId     string       `db:"tank_id"`      // 关联槽体ID
		CalcTime   time.Time    `db:"calc_time"`    // 计算/记录时间
		Cro3GPerL  float64      `db:"cro3_g_per_l"` // 铬酸浓度（g/L，CrO3）
		Cr3GPerL   float64      `db:"cr3_g_per_l"`  // 三价铬浓度（g/L，Cr3+）
		TankVolume float64      `db:"tank_volume"`  // 当前槽液体积（升）
		Source     string       `db:"source"`       // 数据来源：init=初始化，calc=模型计算，lab_override=化验覆盖
		Remark     string       `db:"remark"`       // 备注
		CreatedAt  time.Time    `db:"created_at"`   // 创建时间
		DeletedAt  sql.NullTime `db:"deleted_at"`   // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newPlateModelStateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlateModelStateModel {
	return &defaultPlateModelStateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`plate_model_state`",
	}
}

func (m *defaultPlateModelStateModel) Delete(ctx context.Context, id int64) error {
	platingPlateModelStateIdKey := fmt.Sprintf("%s%v", cachePlatingPlateModelStateIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingPlateModelStateIdKey)
	return err
}

func (m *defaultPlateModelStateModel) FindOne(ctx context.Context, id int64) (*PlateModelState, error) {
	platingPlateModelStateIdKey := fmt.Sprintf("%s%v", cachePlatingPlateModelStateIdPrefix, id)
	var resp PlateModelState
	err := m.QueryRowCtx(ctx, &resp, platingPlateModelStateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateModelStateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlateModelStateModel) Insert(ctx context.Context, data *PlateModelState) (sql.Result, error) {
	platingPlateModelStateIdKey := fmt.Sprintf("%s%v", cachePlatingPlateModelStateIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, plateModelStateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TankId, data.CalcTime, data.Cro3GPerL, data.Cr3GPerL, data.TankVolume, data.Source, data.Remark, data.DeletedAt)
	}, platingPlateModelStateIdKey)
	return ret, err
}

func (m *defaultPlateModelStateModel) Update(ctx context.Context, data *PlateModelState) error {
	platingPlateModelStateIdKey := fmt.Sprintf("%s%v", cachePlatingPlateModelStateIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, plateModelStateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TankId, data.CalcTime, data.Cro3GPerL, data.Cr3GPerL, data.TankVolume, data.Source, data.Remark, data.DeletedAt, data.Id)
	}, platingPlateModelStateIdKey)
	return err
}

func (m *defaultPlateModelStateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingPlateModelStateIdPrefix, primary)
}

func (m *defaultPlateModelStateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", plateModelStateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlateModelStateModel) tableName() string {
	return m.table
}
