// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "go-zero-admin/internal/handler/auth"
	systemapi "go-zero-admin/internal/handler/system/api"
	systemdict "go-zero-admin/internal/handler/system/dict"
	systemfile "go-zero-admin/internal/handler/system/file"
	systemlog "go-zero-admin/internal/handler/system/log"
	systemmenu "go-zero-admin/internal/handler/system/menu"
	systemrole "go-zero-admin/internal/handler/system/role"
	systemuser "go-zero-admin/internal/handler/system/user"
	"go-zero-admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/changePassword",
					Handler: auth.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userInfo",
					Handler: auth.GetCurrentUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api",
					Handler: systemapi.CreateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api",
					Handler: systemapi.ListApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/:id",
					Handler: systemapi.UpdateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/:id",
					Handler: systemapi.DeleteApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/all",
					Handler: systemapi.ListAllApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/dict/data",
					Handler: systemdict.CreateDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dict/data/:dictType",
					Handler: systemdict.GetDictDataByTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/dict/data/:id",
					Handler: systemdict.UpdateDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/dict/data/:id",
					Handler: systemdict.DeleteDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dict/type",
					Handler: systemdict.CreateDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dict/type",
					Handler: systemdict.ListDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/dict/type/:id",
					Handler: systemdict.UpdateDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/dict/type/:id",
					Handler: systemdict.DeleteDictTypeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/file",
					Handler: systemfile.ListFileHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/file/:id",
					Handler: systemfile.DeleteFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: systemfile.UploadFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/log/login",
					Handler: systemlog.ListLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/log/login/clear",
					Handler: systemlog.ClearLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/log/oper",
					Handler: systemlog.ListOperLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/log/oper/clear",
					Handler: systemlog.ClearOperLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/menu",
					Handler: systemmenu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/menu/:id",
					Handler: systemmenu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/menu/:id",
					Handler: systemmenu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/current",
					Handler: systemmenu.GetCurrentUserMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/tree",
					Handler: systemmenu.GetMenuTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/role",
					Handler: systemrole.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role",
					Handler: systemrole.ListRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/:id",
					Handler: systemrole.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/role/:id",
					Handler: systemrole.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/:id",
					Handler: systemrole.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/:id/permissions",
					Handler: systemrole.UpdateRolePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/all",
					Handler: systemrole.ListAllRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: systemuser.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: systemuser.ListUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/:id",
					Handler: systemuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/:id",
					Handler: systemuser.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: systemuser.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/:id/reset-password",
					Handler: systemuser.ResetPasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)
}
