// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "plating/internal/handler/auth"
	plateevent "plating/internal/handler/plate/event"
	platestate "plating/internal/handler/plate/state"
	platetank "plating/internal/handler/plate/tank"
	systemapi "plating/internal/handler/system/api"
	systemdict "plating/internal/handler/system/dict"
	systemfile "plating/internal/handler/system/file"
	systemlog "plating/internal/handler/system/log"
	systemmenu "plating/internal/handler/system/menu"
	systemrole "plating/internal/handler/system/role"
	systemuser "plating/internal/handler/system/user"
	"plating/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/changePassword",
					Handler: auth.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userInfo",
					Handler: auth.GetCurrentUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/event/dosing",
					Handler: plateevent.CreateDosingEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/event/dosing",
					Handler: plateevent.ListDosingEventHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/event/dosing/:id",
					Handler: plateevent.DeleteDosingEventHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/event/production",
					Handler: plateevent.CreateProductionEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/event/production",
					Handler: plateevent.ListProductionEventHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/event/production/:id",
					Handler: plateevent.DeleteProductionEventHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/event/trigger-calc",
					Handler: plateevent.TriggerCalcHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/event/water",
					Handler: plateevent.CreateWaterEventHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/event/water",
					Handler: plateevent.ListWaterEventHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/event/water/:id",
					Handler: plateevent.DeleteWaterEventHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/plating"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/state/:tankId",
					Handler: platestate.GetLatestStateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/state/export",
					Handler: platestate.ExportStateReportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/state/override",
					Handler: platestate.OverrideStateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/state/trend",
					Handler: platestate.GetStateTrendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/plating"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/tank",
					Handler: platetank.CreateTankConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tank",
					Handler: platetank.ListTankConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/tank/:tankId",
					Handler: platetank.UpdateTankConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/tank/:tankId",
					Handler: platetank.DeleteTankConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tank/:tankId",
					Handler: platetank.GetTankConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tank/init-state",
					Handler: platetank.InitModelStateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/plating"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api",
					Handler: systemapi.CreateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api",
					Handler: systemapi.ListApiHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/:id",
					Handler: systemapi.UpdateApiHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/:id",
					Handler: systemapi.DeleteApiHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/all",
					Handler: systemapi.ListAllApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/dict/data",
					Handler: systemdict.CreateDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dict/data/:dictType",
					Handler: systemdict.GetDictDataByTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/dict/data/:id",
					Handler: systemdict.UpdateDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/dict/data/:id",
					Handler: systemdict.DeleteDictDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dict/type",
					Handler: systemdict.CreateDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/dict/type",
					Handler: systemdict.ListDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/dict/type/:id",
					Handler: systemdict.UpdateDictTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/dict/type/:id",
					Handler: systemdict.DeleteDictTypeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/file",
					Handler: systemfile.ListFileHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/file/:id",
					Handler: systemfile.DeleteFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/file/upload",
					Handler: systemfile.UploadFileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/log/login",
					Handler: systemlog.ListLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/log/login/clear",
					Handler: systemlog.ClearLoginLogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/log/oper",
					Handler: systemlog.ListOperLogHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/log/oper/clear",
					Handler: systemlog.ClearOperLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/menu",
					Handler: systemmenu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/menu/:id",
					Handler: systemmenu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/menu/:id",
					Handler: systemmenu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/current",
					Handler: systemmenu.GetCurrentUserMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/tree",
					Handler: systemmenu.GetMenuTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/role",
					Handler: systemrole.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role",
					Handler: systemrole.ListRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/:id",
					Handler: systemrole.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/role/:id",
					Handler: systemrole.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/:id",
					Handler: systemrole.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/all",
					Handler: systemrole.ListAllRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: systemuser.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: systemuser.ListUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/:id",
					Handler: systemuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/:id",
					Handler: systemuser.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: systemuser.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/:id/reset-password",
					Handler: systemuser.ResetPasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/system"),
	)
}
