// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysMenuFieldNames          = builder.RawFieldNames(&SysMenu{})
	sysMenuRows                = strings.Join(sysMenuFieldNames, ",")
	sysMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(sysMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(sysMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingSysMenuIdPrefix = "cache:plating:sysMenu:id:"
)

type (
	sysMenuModel interface {
		Insert(ctx context.Context, data *SysMenu) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysMenu, error)
		Update(ctx context.Context, data *SysMenu) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysMenuModel struct {
		sqlc.CachedConn
		table string
	}

	SysMenu struct {
		Id         int64        `db:"id"`         // 菜单ID
		ParentId   int64        `db:"parent_id"`  // 父菜单ID，0表示顶级
		Name       string       `db:"name"`       // 菜单名称
		MenuPath   string       `db:"menu_path"`  // 路由路径
		Component  string       `db:"component"`  // 前端组件路径
		Icon       string       `db:"icon"`       // 菜单图标
		MenuType   int64        `db:"menu_type"`  // 菜单类型：0=目录，1=菜单，2=按钮
		Permission string       `db:"permission"` // 权限标识符，如：system:user:list
		Sort       int64        `db:"sort"`       // 排序值，越小越靠前
		Visible    int64        `db:"visible"`    // 是否可见：1=可见，0=隐藏
		Status     int64        `db:"status"`     // 状态：1=启用，0=禁用
		Remark     string       `db:"remark"`     // 备注
		CreatedAt  time.Time    `db:"created_at"` // 创建时间
		UpdatedAt  time.Time    `db:"updated_at"` // 更新时间
		DeletedAt  sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysMenuModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysMenuModel {
	return &defaultSysMenuModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_menu`",
	}
}

func (m *defaultSysMenuModel) Delete(ctx context.Context, id int64) error {
	platingSysMenuIdKey := fmt.Sprintf("%s%v", cachePlatingSysMenuIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingSysMenuIdKey)
	return err
}

func (m *defaultSysMenuModel) FindOne(ctx context.Context, id int64) (*SysMenu, error) {
	platingSysMenuIdKey := fmt.Sprintf("%s%v", cachePlatingSysMenuIdPrefix, id)
	var resp SysMenu
	err := m.QueryRowCtx(ctx, &resp, platingSysMenuIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysMenuRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) Insert(ctx context.Context, data *SysMenu) (sql.Result, error) {
	platingSysMenuIdKey := fmt.Sprintf("%s%v", cachePlatingSysMenuIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysMenuRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.MenuPath, data.Component, data.Icon, data.MenuType, data.Permission, data.Sort, data.Visible, data.Status, data.Remark, data.DeletedAt)
	}, platingSysMenuIdKey)
	return ret, err
}

func (m *defaultSysMenuModel) Update(ctx context.Context, data *SysMenu) error {
	platingSysMenuIdKey := fmt.Sprintf("%s%v", cachePlatingSysMenuIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysMenuRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.MenuPath, data.Component, data.Icon, data.MenuType, data.Permission, data.Sort, data.Visible, data.Status, data.Remark, data.DeletedAt, data.Id)
	}, platingSysMenuIdKey)
	return err
}

func (m *defaultSysMenuModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingSysMenuIdPrefix, primary)
}

func (m *defaultSysMenuModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysMenuRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysMenuModel) tableName() string {
	return m.table
}
