// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysApiFieldNames          = builder.RawFieldNames(&SysApi{})
	sysApiRows                = strings.Join(sysApiFieldNames, ",")
	sysApiRowsExpectAutoSet   = strings.Join(stringx.Remove(sysApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysApiRowsWithPlaceHolder = strings.Join(stringx.Remove(sysApiFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingSysApiIdPrefix            = "cache:plating:sysApi:id:"
	cachePlatingSysApiApiPathMethodPrefix = "cache:plating:sysApi:apiPath:method:"
)

type (
	sysApiModel interface {
		Insert(ctx context.Context, data *SysApi) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysApi, error)
		FindOneByApiPathMethod(ctx context.Context, apiPath string, method string) (*SysApi, error)
		Update(ctx context.Context, data *SysApi) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysApiModel struct {
		sqlc.CachedConn
		table string
	}

	SysApi struct {
		Id          int64        `db:"id"`          // 接口ID
		ApiPath     string       `db:"api_path"`    // 接口路径，如：/api/system/user
		Method      string       `db:"method"`      // HTTP方法：GET/POST/PUT/DELETE
		ApiGroup    string       `db:"api_group"`   // 接口分组，如：系统管理
		Description string       `db:"description"` // 接口描述
		CreatedAt   time.Time    `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time    `db:"updated_at"`  // 更新时间
		DeletedAt   sql.NullTime `db:"deleted_at"`  // 软删除时间, 空-未删除，非空为已删除时间
		ApiName     string       `db:"api_name"`    // 接口中文名称
	}
)

func newSysApiModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysApiModel {
	return &defaultSysApiModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_api`",
	}
}

func (m *defaultSysApiModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	platingSysApiApiPathMethodKey := fmt.Sprintf("%s%v:%v", cachePlatingSysApiApiPathMethodPrefix, data.ApiPath, data.Method)
	platingSysApiIdKey := fmt.Sprintf("%s%v", cachePlatingSysApiIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingSysApiApiPathMethodKey, platingSysApiIdKey)
	return err
}

func (m *defaultSysApiModel) FindOne(ctx context.Context, id int64) (*SysApi, error) {
	platingSysApiIdKey := fmt.Sprintf("%s%v", cachePlatingSysApiIdPrefix, id)
	var resp SysApi
	err := m.QueryRowCtx(ctx, &resp, platingSysApiIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysApiRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysApiModel) FindOneByApiPathMethod(ctx context.Context, apiPath string, method string) (*SysApi, error) {
	platingSysApiApiPathMethodKey := fmt.Sprintf("%s%v:%v", cachePlatingSysApiApiPathMethodPrefix, apiPath, method)
	var resp SysApi
	err := m.QueryRowIndexCtx(ctx, &resp, platingSysApiApiPathMethodKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `api_path` = ? and `method` = ? limit 1", sysApiRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, apiPath, method); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysApiModel) Insert(ctx context.Context, data *SysApi) (sql.Result, error) {
	platingSysApiApiPathMethodKey := fmt.Sprintf("%s%v:%v", cachePlatingSysApiApiPathMethodPrefix, data.ApiPath, data.Method)
	platingSysApiIdKey := fmt.Sprintf("%s%v", cachePlatingSysApiIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, sysApiRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ApiPath, data.Method, data.ApiGroup, data.Description, data.DeletedAt, data.ApiName)
	}, platingSysApiApiPathMethodKey, platingSysApiIdKey)
	return ret, err
}

func (m *defaultSysApiModel) Update(ctx context.Context, newData *SysApi) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	platingSysApiApiPathMethodKey := fmt.Sprintf("%s%v:%v", cachePlatingSysApiApiPathMethodPrefix, data.ApiPath, data.Method)
	platingSysApiIdKey := fmt.Sprintf("%s%v", cachePlatingSysApiIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysApiRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ApiPath, newData.Method, newData.ApiGroup, newData.Description, newData.DeletedAt, newData.ApiName, newData.Id)
	}, platingSysApiApiPathMethodKey, platingSysApiIdKey)
	return err
}

func (m *defaultSysApiModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingSysApiIdPrefix, primary)
}

func (m *defaultSysApiModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysApiRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysApiModel) tableName() string {
	return m.table
}
