// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictTypeFieldNames          = builder.RawFieldNames(&SysDictType{})
	sysDictTypeRows                = strings.Join(sysDictTypeFieldNames, ",")
	sysDictTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingSysDictTypeIdPrefix   = "cache:plating:sysDictType:id:"
	cachePlatingSysDictTypeCodePrefix = "cache:plating:sysDictType:code:"
)

type (
	sysDictTypeModel interface {
		Insert(ctx context.Context, data *SysDictType) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysDictType, error)
		FindOneByCode(ctx context.Context, code string) (*SysDictType, error)
		Update(ctx context.Context, data *SysDictType) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysDictTypeModel struct {
		sqlc.CachedConn
		table string
	}

	SysDictType struct {
		Id        int64        `db:"id"`         // 字典类型ID
		Name      string       `db:"name"`       // 字典类型名称
		Code      string       `db:"code"`       // 字典类型编码
		Status    int64        `db:"status"`     // 状态：1=启用，0=禁用
		Remark    string       `db:"remark"`     // 备注
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysDictTypeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysDictTypeModel {
	return &defaultSysDictTypeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_dict_type`",
	}
}

func (m *defaultSysDictTypeModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	platingSysDictTypeCodeKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeCodePrefix, data.Code)
	platingSysDictTypeIdKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingSysDictTypeCodeKey, platingSysDictTypeIdKey)
	return err
}

func (m *defaultSysDictTypeModel) FindOne(ctx context.Context, id int64) (*SysDictType, error) {
	platingSysDictTypeIdKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeIdPrefix, id)
	var resp SysDictType
	err := m.QueryRowCtx(ctx, &resp, platingSysDictTypeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictTypeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) FindOneByCode(ctx context.Context, code string) (*SysDictType, error) {
	platingSysDictTypeCodeKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeCodePrefix, code)
	var resp SysDictType
	err := m.QueryRowIndexCtx(ctx, &resp, platingSysDictTypeCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", sysDictTypeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) Insert(ctx context.Context, data *SysDictType) (sql.Result, error) {
	platingSysDictTypeCodeKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeCodePrefix, data.Code)
	platingSysDictTypeIdKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysDictTypeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Code, data.Status, data.Remark, data.DeletedAt)
	}, platingSysDictTypeCodeKey, platingSysDictTypeIdKey)
	return ret, err
}

func (m *defaultSysDictTypeModel) Update(ctx context.Context, newData *SysDictType) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	platingSysDictTypeCodeKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeCodePrefix, data.Code)
	platingSysDictTypeIdKey := fmt.Sprintf("%s%v", cachePlatingSysDictTypeIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDictTypeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Code, newData.Status, newData.Remark, newData.DeletedAt, newData.Id)
	}, platingSysDictTypeCodeKey, platingSysDictTypeIdKey)
	return err
}

func (m *defaultSysDictTypeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingSysDictTypeIdPrefix, primary)
}

func (m *defaultSysDictTypeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDictTypeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDictTypeModel) tableName() string {
	return m.table
}
