// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysOperLogFieldNames          = builder.RawFieldNames(&SysOperLog{})
	sysOperLogRows                = strings.Join(sysOperLogFieldNames, ",")
	sysOperLogRowsExpectAutoSet   = strings.Join(stringx.Remove(sysOperLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysOperLogRowsWithPlaceHolder = strings.Join(stringx.Remove(sysOperLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingSysOperLogIdPrefix = "cache:plating:sysOperLog:id:"
)

type (
	sysOperLogModel interface {
		Insert(ctx context.Context, data *SysOperLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysOperLog, error)
		Update(ctx context.Context, data *SysOperLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysOperLogModel struct {
		sqlc.CachedConn
		table string
	}

	SysOperLog struct {
		Id            int64          `db:"id"`             // 操作日志ID
		Title         string         `db:"title"`          // 操作模块标题
		BusinessType  int64          `db:"business_type"`  // 业务类型：0=其他，1=新增，2=修改，3=删除，4=查询
		Method        string         `db:"method"`         // 方法名称
		RequestMethod string         `db:"request_method"` // 请求方式：GET/POST/PUT/DELETE
		OperatorType  int64          `db:"operator_type"`  // 操作人类型：0=其他，1=后台用户，2=手机端用户
		OperatorName  string         `db:"operator_name"`  // 操作人员名称
		OperatorId    int64          `db:"operator_id"`    // 操作人员ID
		DeptName      string         `db:"dept_name"`      // 部门名称
		OperUrl       string         `db:"oper_url"`       // 请求URL
		OperIp        string         `db:"oper_ip"`        // 操作IP
		OperParam     sql.NullString `db:"oper_param"`     // 请求参数（JSON）
		JsonResult    sql.NullString `db:"json_result"`    // 返回结果（JSON）
		Status        int64          `db:"status"`         // 操作状态：1=成功，0=失败
		ErrorMsg      string         `db:"error_msg"`      // 错误消息
		OperTime      time.Time      `db:"oper_time"`      // 操作时间
		DeletedAt     sql.NullTime   `db:"deleted_at"`     // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysOperLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysOperLogModel {
	return &defaultSysOperLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_oper_log`",
	}
}

func (m *defaultSysOperLogModel) Delete(ctx context.Context, id int64) error {
	platingSysOperLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysOperLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingSysOperLogIdKey)
	return err
}

func (m *defaultSysOperLogModel) FindOne(ctx context.Context, id int64) (*SysOperLog, error) {
	platingSysOperLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysOperLogIdPrefix, id)
	var resp SysOperLog
	err := m.QueryRowCtx(ctx, &resp, platingSysOperLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysOperLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysOperLogModel) Insert(ctx context.Context, data *SysOperLog) (sql.Result, error) {
	platingSysOperLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysOperLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysOperLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.BusinessType, data.Method, data.RequestMethod, data.OperatorType, data.OperatorName, data.OperatorId, data.DeptName, data.OperUrl, data.OperIp, data.OperParam, data.JsonResult, data.Status, data.ErrorMsg, data.OperTime, data.DeletedAt)
	}, platingSysOperLogIdKey)
	return ret, err
}

func (m *defaultSysOperLogModel) Update(ctx context.Context, data *SysOperLog) error {
	platingSysOperLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysOperLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysOperLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Title, data.BusinessType, data.Method, data.RequestMethod, data.OperatorType, data.OperatorName, data.OperatorId, data.DeptName, data.OperUrl, data.OperIp, data.OperParam, data.JsonResult, data.Status, data.ErrorMsg, data.OperTime, data.DeletedAt, data.Id)
	}, platingSysOperLogIdKey)
	return err
}

func (m *defaultSysOperLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingSysOperLogIdPrefix, primary)
}

func (m *defaultSysOperLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysOperLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysOperLogModel) tableName() string {
	return m.table
}
