// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysLoginLogFieldNames          = builder.RawFieldNames(&SysLoginLog{})
	sysLoginLogRows                = strings.Join(sysLoginLogFieldNames, ",")
	sysLoginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(sysLoginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysLoginLogRowsWithPlaceHolder = strings.Join(stringx.Remove(sysLoginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingSysLoginLogIdPrefix = "cache:plating:sysLoginLog:id:"
)

type (
	sysLoginLogModel interface {
		Insert(ctx context.Context, data *SysLoginLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysLoginLog, error)
		Update(ctx context.Context, data *SysLoginLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysLoginLogModel struct {
		sqlc.CachedConn
		table string
	}

	SysLoginLog struct {
		Id        int64        `db:"id"`         // 日志ID
		UserId    int64        `db:"user_id"`    // 用户ID
		Username  string       `db:"username"`   // 用户名
		Ip        string       `db:"ip"`         // 登录IP
		Location  string       `db:"location"`   // 登录地点
		Browser   string       `db:"browser"`    // 浏览器
		Os        string       `db:"os"`         // 操作系统
		Status    int64        `db:"status"`     // 登录状态：1=成功，0=失败
		Msg       string       `db:"msg"`        // 提示消息
		LoginTime time.Time    `db:"login_time"` // 登录时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysLoginLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysLoginLogModel {
	return &defaultSysLoginLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_login_log`",
	}
}

func (m *defaultSysLoginLogModel) Delete(ctx context.Context, id int64) error {
	platingSysLoginLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysLoginLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingSysLoginLogIdKey)
	return err
}

func (m *defaultSysLoginLogModel) FindOne(ctx context.Context, id int64) (*SysLoginLog, error) {
	platingSysLoginLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysLoginLogIdPrefix, id)
	var resp SysLoginLog
	err := m.QueryRowCtx(ctx, &resp, platingSysLoginLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysLoginLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysLoginLogModel) Insert(ctx context.Context, data *SysLoginLog) (sql.Result, error) {
	platingSysLoginLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysLoginLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysLoginLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Ip, data.Location, data.Browser, data.Os, data.Status, data.Msg, data.LoginTime, data.DeletedAt)
	}, platingSysLoginLogIdKey)
	return ret, err
}

func (m *defaultSysLoginLogModel) Update(ctx context.Context, data *SysLoginLog) error {
	platingSysLoginLogIdKey := fmt.Sprintf("%s%v", cachePlatingSysLoginLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysLoginLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Ip, data.Location, data.Browser, data.Os, data.Status, data.Msg, data.LoginTime, data.DeletedAt, data.Id)
	}, platingSysLoginLogIdKey)
	return err
}

func (m *defaultSysLoginLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingSysLoginLogIdPrefix, primary)
}

func (m *defaultSysLoginLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysLoginLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysLoginLogModel) tableName() string {
	return m.table
}
