// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysFileFieldNames          = builder.RawFieldNames(&SysFile{})
	sysFileRows                = strings.Join(sysFileFieldNames, ",")
	sysFileRowsExpectAutoSet   = strings.Join(stringx.Remove(sysFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysFileRowsWithPlaceHolder = strings.Join(stringx.Remove(sysFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatingSysFileIdPrefix = "cache:plating:sysFile:id:"
)

type (
	sysFileModel interface {
		Insert(ctx context.Context, data *SysFile) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysFile, error)
		Update(ctx context.Context, data *SysFile) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysFileModel struct {
		sqlc.CachedConn
		table string
	}

	SysFile struct {
		Id         int64        `db:"id"`          // 文件ID
		Filename   string       `db:"filename"`    // 存储文件名（UUID生成）
		OriginName string       `db:"origin_name"` // 原始文件名
		FilePath   string       `db:"file_path"`   // 文件存储路径
		FileUrl    string       `db:"file_url"`    // 文件访问URL
		FileSize   int64        `db:"file_size"`   // 文件大小（字节）
		FileType   string       `db:"file_type"`   // 文件类型/MIME类型
		UploaderId int64        `db:"uploader_id"` // 上传人用户ID
		CreatedAt  time.Time    `db:"created_at"`  // 上传时间
		DeletedAt  sql.NullTime `db:"deleted_at"`  // 软删除时间, 空-未删除，非空为已删除时间
	}
)

func newSysFileModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysFileModel {
	return &defaultSysFileModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_file`",
	}
}

func (m *defaultSysFileModel) Delete(ctx context.Context, id int64) error {
	platingSysFileIdKey := fmt.Sprintf("%s%v", cachePlatingSysFileIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, platingSysFileIdKey)
	return err
}

func (m *defaultSysFileModel) FindOne(ctx context.Context, id int64) (*SysFile, error) {
	platingSysFileIdKey := fmt.Sprintf("%s%v", cachePlatingSysFileIdPrefix, id)
	var resp SysFile
	err := m.QueryRowCtx(ctx, &resp, platingSysFileIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysFileRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysFileModel) Insert(ctx context.Context, data *SysFile) (sql.Result, error) {
	platingSysFileIdKey := fmt.Sprintf("%s%v", cachePlatingSysFileIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysFileRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Filename, data.OriginName, data.FilePath, data.FileUrl, data.FileSize, data.FileType, data.UploaderId, data.DeletedAt)
	}, platingSysFileIdKey)
	return ret, err
}

func (m *defaultSysFileModel) Update(ctx context.Context, data *SysFile) error {
	platingSysFileIdKey := fmt.Sprintf("%s%v", cachePlatingSysFileIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysFileRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Filename, data.OriginName, data.FilePath, data.FileUrl, data.FileSize, data.FileType, data.UploaderId, data.DeletedAt, data.Id)
	}, platingSysFileIdKey)
	return err
}

func (m *defaultSysFileModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatingSysFileIdPrefix, primary)
}

func (m *defaultSysFileModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysFileRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysFileModel) tableName() string {
	return m.table
}
